### PR TITLE
added custom color props for primary and secondary toast buttons

### PR DESCRIPTION
**Pull request by SandraRodgers**

### CODE REVIEW

**Comment by SandraRodgers** [comment]
This is an attempt to add the enhancement requested in Issue 21 (https://github.com/acidjazz/tv-toast/issues/21). If this isn't the best way to fix this, I would be happy to take feedback and try again.

**Comment by acidjazz** [comment]
@SandraRodgers Thanks for the PR! I'll look it over and test it ASAP

**Comment by SandraRodgers** [comment]
@acidjazz Great! By the way, it's a great component. Very clean and easy to use.

**Comment by acidjazz** [comment]
This looks great so far, I wonder if we could:

 - [ ] move the other classes that style the button into this ( the focus classes and `active:bg-gray-50`)
 - [ ] if we could have these classes stack w/ what you pass through, so that you can style it w/out having to specify all of them.

**Comment by SandraRodgers** [comment]
Ok, I have attempted to make the classes 'stackable' like you suggested. I wasn't sure about names for the props so you might want to change those (or tell me what to change them to).... I tried not to make them too long but still understandable regarding the type of toast (single action or multiple). Also, I had forgotten to add the props for the single action toast so added that in this commit. Let me know if you have any other suggestions to make this better!

**Comment by acidjazz** [comment]
@SandraRodgers names are great! this looks good so far, I'll run through it and test stuff ASAP!

**Comment by acidjazz** [comment]
@SandraRodgers BTW I actually went back to your simpler setup realizing stacking isn't as realistic as I thought, i added some detail in the readme to let people know what defaults will be swapped out.

**Comment by SandraRodgers** [comment]
That's good, I liked the stacking idea but I can see how having just one prop for each button might be more straightforward for someone looking to style the buttons. Happy I was able to contribute!

**Pull request merged**
